export const FILTER_TRANSFORMERS = 'FILTER_TRANSFORMERS';
export const REQUEST_TRANSFORMERS_SUCCESS = 'REQUEST_TRANSFORMERS_SUCCESS';
export const POST_TRANSFORMER_SUCCESS = 'POST_TRANSFORMER_SUCCESS';
export const DELETE_TRANSFORMER_SUCCESS = 'DELETE_TRANSFORMER_SUCCESS';
